version: "3.8"
services:
  nginx:
    hostname: nginx-gql-optimisation
    container_name: nginx-gql-optimisation
    restart: unless-stopped
    build:
      context: ./nginx/
    ports:
      - $NGINX_PORT:80
    depends_on:
      - backend
  backend:
    hostname: backend-gql-optimisation
    container_name: backend-gql-optimisation-$BUILD_TYPE
    restart: unless-stopped
    build:
      context: ./backend/
      target: $BUILD_TYPE
    environment:
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
    volumes:
      - ./backend/src:/usr/app/src
    depends_on:
      - db
  db:
    hostname: db-gql-optimisation
    container_name: db-gql-optimisation
    restart: unless-stopped
    build:
      context: ./db/
    environment:
      MARIADB_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MARIADB_DATABASE: $DB_NAME
      MARIADB_USER: $DB_USER
      MARIADB_PASSWORD: $DB_PASSWORD
    ports:
      - $DB_PORT:3306
    volumes:
      - ./db/data:/var/lib/mysql
